export const Itemdata = [
  {
    id: 1,
    rname: "Light Blue Jeans",
    imgdata: "https://res.cloudinary.com/dsmlde0pv/image/upload/v1659070199/item-01_cxt1a0.jpg",
    type:"Lorem Ipsum is simply dummy text",
    somedata:"1100 + order placed from here recently",
    price: "50",
    qnty: 0,
  },
  {
    id: 2,
    rname: "Dark Blue Jeans",
    imgdata: "https://res.cloudinary.com/dsmlde0pv/image/upload/v1659070199/item-02_xqfdyn.jpg",
    type:"Lorem Ipsum is simply dummy text",
    somedata:"1100 + order placed from here recently",
    price: "30",
    qnty: 0,
  },
  {
    id: 3,
    rname: " Blue Jacket",
    imgdata: "https://res.cloudinary.com/dsmlde0pv/image/upload/v1659070199/item-03_iibijv.jpg",
    type:"Lorem Ipsum is simply dummy text",
    somedata:"1100 + order placed from here recently",
    price: "40",
    qnty: 0,
  },
  {
    id: 4,
    rname: "Green Purse",
    imgdata: "https://res.cloudinary.com/dsmlde0pv/image/upload/v1659070200/item-04_qysqfh.jpg",
    type:"Lorem Ipsum is simply dummy text",
    somedata:"1100 + order placed from here recently",
    price: "35",
    qnty: 0,
  },
  {
    id: 5,
    rname: "Pink Purse",
    imgdata: "https://res.cloudinary.com/dsmlde0pv/image/upload/v1659070200/item-05_onkcgz.jpg",
    type:"Lorem Ipsum is simply dummy text",
    somedata:"1100 + order placed from here recently",
    price: "37",
    qnty: 0,
  },
  {
    id: 6,
    rname: "T-shirt",
    imgdata: "https://res.cloudinary.com/dsmlde0pv/image/upload/v1659070200/tshirt_aiiaqy.jpg",
    type:"Lorem Ipsum is simply dummy text",
    somedata:"1100 + order placed from here recently",
    price: "10",
    qnty: 0,
  },
  {
    id: 7,
    rname: "Shirt",
    imgdata: "https://res.cloudinary.com/dsmlde0pv/image/upload/v1659070200/shirt_amvwq9.jpg",
    type:"Lorem Ipsum is simply dummy text",
    somedata:"1100 + order placed from here recently",
    price: "12",
    qnty: 0,
  },
  {
    id: 8,
    rname: "Jeans",
    imgdata: "https://res.cloudinary.com/dsmlde0pv/image/upload/v1659070200/jeans_ls9rvk.jpg",
    type:"Lorem Ipsum is simply dummy text",
    somedata:"1100 + order placed from here recently",
    price: "50",
    qnty: 0,
  },
  
]

export const productData = [
  {
    id: 1,
    rname: "Men's Jacket",
    imgdata: "https://res.cloudinary.com/dsmlde0pv/image/upload/v1659070284/product_1_ljvf7o.png",
    price: "50",
    category:"men's",
    qnty: 0,
  },
  {
    id: 2,
    rname: "Shopping bag",
    imgdata: "https://res.cloudinary.com/dsmlde0pv/image/upload/v1659070284/product_2_nsn40t.png",
    price: "25",
    category:"women's",
    qnty: 0,
  },
  {
    id: 3,
    rname: "Swetshirt",
    imgdata: "https://res.cloudinary.com/dsmlde0pv/image/upload/v1659070284/product_3_lgiygk.png",
    price: "45",
    category:"women's",
    qnty: 0,
  },
  {
    id: 4,
    rname: "Traveling Bag",
    imgdata: "https://res.cloudinary.com/dsmlde0pv/image/upload/v1659070284/product_4_wa3mfh.png",
    price: "30",
    category:"accessories",
    qnty: 0,
  },
  {
    id: 5,
    rname: "Sneaker",
    imgdata: "https://res.cloudinary.com/dsmlde0pv/image/upload/v1659070284/product_5_mdihpj.png",
    category:"women's",
    price: "85",
    qnty: 0,
  },
  {
    id: 6,
    rname: "Sunglasses",
    imgdata: "https://res.cloudinary.com/dsmlde0pv/image/upload/v1659070284/product_6_ahosoh.png",
    price: "10",
    category:"accessories",
    qnty: 0,
  },
  {
    id: 7,
    rname: "Swetshirt",
    imgdata: "https://res.cloudinary.com/dsmlde0pv/image/upload/v1659070284/product_7_zqncwq.png",
    price: "40",
    category:"women's",
    qnty: 0,
  },
  {
    id: 8,
    rname: "Purse",
    imgdata: "https://res.cloudinary.com/dsmlde0pv/image/upload/v1659070284/product_8_v0ejy9.png",
    price: "50",
    category:"accessories",
    qnty: 0,
  },
  {
    id: 9,
    rname: "Shirt",
    imgdata: "https://res.cloudinary.com/dsmlde0pv/image/upload/v1659070284/product_9_dkmv8v.png",
    price: "42",
    category:"men's",
    qnty: 0,
  },
  {
    id: 10,
    rname: "Swetshirt",
    imgdata: "https://res.cloudinary.com/dsmlde0pv/image/upload/v1659070284/product_10_xhejbb.png",
    price: "40",
    category:"men's",
    qnty: 0,
  },
  
]

